# Generated by Django 4.2 on 2023-06-01 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("flags", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="domain",
            old_name="expired_at",
            new_name="expire_at",
        ),
    ]
