# Generated by Django 4.2 on 2023-06-01 12:28

import authentication.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_remove_user_username_alter_user_email"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", authentication.models.UserManager()),
            ],
        ),
    ]
